name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Django unit tests
      run: |
        pip3 install --user django
        pip3 install webdriver-manager
        pip3 install get-chrome-driver --upgrade
        pip3 install -r selenium/requirements.txt
        python3 manage.py runserver && python3 manage.py test