name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Django unit tests
      run: |
        pip install --user django
        pip install webdriver-manager
        pip install get-chrome-driver --upgrade
        pip install -r selenium/requirements.txt
        python manage.py test